Repository Caleydo/ordino, pull requests merged in 2021-04, with the labels that each got.

#282 Replace react-scroll with Bootstrap 4 scrollspy
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/menu/StartMenuReact.js
  dist/internal/menu/StartMenuReact.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/scss/components/_StartMenuReact.scss
  package.json
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/menu/StartMenuReact.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/scss/components/_StartMenuReact.scss
Labels: release: minor

#285 Minor compatibility fixes
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/scss/components/_StartMenuReact.scss
  src/internal/components/dataset/NamedSetList.tsx
  src/scss/components/_StartMenuReact.scss
Labels: type: refactor

#286 Move upload dataset card and components to tdp_uploaded_data
  dist/components/ListItemDropdown.d.ts
  dist/components/ListItemDropdown.js
  dist/components/ListItemDropdown.js.map
  dist/components/index.d.ts
  dist/components/index.js
  dist/components/index.js.map
  dist/hooks/useAsync.d.ts
  dist/internal/cmds.d.ts
  dist/internal/components/common/ListItemDropdown.js.map
  dist/internal/components/common/index.d.ts
  dist/internal/components/common/index.js
  dist/internal/components/common/index.js.map
  dist/internal/components/dataset/DatasetDropzone.d.ts
  dist/internal/components/dataset/DatasetDropzone.js
  dist/internal/components/dataset/DatasetDropzone.js.map
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/internal/components/dataset/UploadDatasetCard.d.ts
  dist/internal/components/dataset/UploadDatasetCard.js
  dist/internal/components/dataset/UploadDatasetCard.js.map
  dist/internal/components/dataset/UploadDatasetListItem.d.ts
  dist/internal/components/dataset/UploadDatasetListItem.js
  dist/internal/components/dataset/UploadDatasetListItem.js.map
  dist/internal/components/dataset/index.d.ts
  dist/internal/components/dataset/index.js
  dist/internal/components/dataset/index.js.map
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/components/session/TemporarySessionCard.js
  dist/internal/components/session/TemporarySessionCard.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  src/components/ListItemDropdown.tsx
  src/components/index.ts
  src/internal/components/common/index.ts
  src/internal/components/dataset/DatasetDropzone.tsx
  src/internal/components/dataset/NamedSetList.tsx
  src/internal/components/dataset/UploadDatasetCard.tsx
  src/internal/components/dataset/UploadDatasetListItem.tsx
  src/internal/components/dataset/index.ts
  src/internal/components/session/CurrentSessionCard.tsx
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/components/session/TemporarySessionCard.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
Labels: release: minor, type: feature

#291 Update to Bootstrap v4 - Additional Changes
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  src/internal/ViewWrapper.ts
Labels: release: major

#293 Fix wrong history/breadcrumb title when replacing detail views
  dist/internal/OrdinoApp.d.ts
  dist/internal/OrdinoApp.js
  dist/internal/OrdinoApp.js.map
  dist/internal/ViewWrapper.d.ts
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  dist/internal/cmds.d.ts
  dist/internal/cmds.js
  dist/internal/cmds.js.map
  dist/internal/components/navigation/OrdinoBreadcrumbs.d.ts
  dist/internal/components/navigation/OrdinoBreadcrumbs.js
  dist/internal/components/navigation/OrdinoBreadcrumbs.js.map
  dist/internal/components/navigation/index.d.ts
  dist/internal/components/navigation/index.js
  dist/internal/components/navigation/index.js.map
  src/internal/OrdinoApp.tsx
  src/internal/ViewWrapper.ts
  src/internal/cmds.ts
  src/internal/components/navigation/OrdinoBreadcrumbs.tsx
  src/internal/components/navigation/index.ts
Labels: type: bug
