Repository Caleydo/ordino, pull requests merged in 2021-03, with the labels that each got.

#271 Add the default `All` named set
  dist/internal/components/dataset/NamedSetList.d.ts
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  src/internal/components/dataset/NamedSetList.tsx
Labels: release: minor, type: refactor

#272 Refactor how to start new Ordino session
  .yo-rc.json
  dist/app/Ordino.d.ts
  dist/app/Ordino.js
  dist/app/Ordino.js.map
  dist/base/index.d.ts
  dist/base/index.js
  dist/base/index.js.map
  dist/internal/IOrdinoApp.d.ts
  dist/internal/OrdinoApp copy.d.ts
  dist/internal/OrdinoApp copy.js
  dist/internal/OrdinoApp copy.js.map
  dist/internal/OrdinoApp.d.ts
  dist/internal/OrdinoApp.js
  dist/internal/OrdinoApp.js.map
  dist/internal/OrdinoAppComponent.d.ts
  dist/internal/OrdinoAppComponent.js
  dist/internal/OrdinoAppComponent.js.map
  dist/internal/cmds.d.ts
  dist/internal/components/dataset/NamedSetList.d.ts
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/internal/components/session/CommonSessionCard.js
  dist/internal/components/session/CommonSessionCard.js.map
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/components/session/SessionDropzone.js
  dist/internal/components/session/SessionDropzone.js.map
  dist/internal/components/session/TemporarySessionCard.js
  dist/internal/components/session/TemporarySessionCard.js.map
  dist/internal/constants.d.ts
  dist/internal/constants.js
  dist/internal/constants.js.map
  dist/internal/index.d.ts
  dist/internal/index.js
  dist/internal/index.js.map
  dist/phovea.js
  dist/phovea.js.map
  dist/templates/welcome_view.html
  src/app/Ordino.tsx
  src/base/IWelcomeView.ts
  src/base/WelcomeView.ts
  src/base/index.ts
  src/internal/IOrdinoApp.ts
  src/internal/OrdinoApp.ts
  src/internal/OrdinoApp.tsx
  src/internal/components/dataset/NamedSetList.tsx
  src/internal/components/session/CommonSessionCard.tsx
  src/internal/components/session/CurrentSessionCard.tsx
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/components/session/SessionDropzone.tsx
  src/internal/components/session/TemporarySessionCard.tsx
  src/internal/constants.ts
  src/internal/index.ts
  src/phovea.ts
  src/templates/welcome_view.html
Labels: type: refactor

#276 Fix SASS `$theme-color` assignment
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  dist/scss/abstracts/_variables.scss
  dist/scss/components/_StartMenuReact.scss
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
  src/scss/abstracts/_variables.scss
  src/scss/components/_StartMenuReact.scss
Labels: release: minor, type: refactor

#273 Add edit and delete actions to the NamedSetList
  dist/base/IWelcomeView.d.ts
  dist/base/IWelcomeView.js
  dist/base/IWelcomeView.js.map
  dist/base/WelcomeView.d.ts
  dist/base/WelcomeView.js
  dist/base/WelcomeView.js.map
  dist/internal/cmds.d.ts
  dist/internal/components/dataset/NamedSetList.d.ts
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  src/internal/components/dataset/NamedSetList.tsx
Labels: release: minor, type: refactor

#275 Add footer to the start menu tabs
  dist/components/OrdinoFooter.js
  dist/components/OrdinoFooter.js.map
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/menu/StartMenuReact.js
  dist/internal/menu/StartMenuReact.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  dist/scss/abstracts/_variables.scss
  dist/scss/components/_StartMenuReact.scss
  package.json
  src/components/OrdinoFooter.tsx
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/menu/StartMenuReact.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
  src/scss/abstracts/_variables.scss
  src/scss/components/_StartMenuReact.scss
Labels: release: minor, type: feature, type: refactor

#277 Make bootstrap spacers variable extendable
  dist/scss/abstracts/_variables.scss
  src/scss/abstracts/_variables.scss
Labels: release: minor, type: feature

#278 Fix scrolling behavior of the start menu tabs
  dist/internal/menu/StartMenuReact.js
  dist/internal/menu/StartMenuReact.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  dist/scss/components/_StartMenuReact.scss
  package.json
  src/internal/menu/StartMenuReact.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
  src/scss/components/_StartMenuReact.scss
Labels: release: minor, type: bug

#279 Make header position fixed when start menu is open
  dist/internal/menu/StartMenuReact.js
  dist/internal/menu/StartMenuReact.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/scss/components/_StartMenuReact.scss
  src/internal/menu/StartMenuReact.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/scss/components/_StartMenuReact.scss
Labels: release: minor, type: feature

#280 Start new session when the current temporary session is deleted
  dist/internal/components/session/CommonSessionCard.js
  dist/internal/components/session/CommonSessionCard.js.map
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.js.map
  src/internal/components/session/CommonSessionCard.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
Labels: release: minor, type: bug

#281 Remove export button from Temporary and Saved sessions
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/components/session/TemporarySessionCard.js
  dist/internal/components/session/TemporarySessionCard.js.map
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/components/session/TemporarySessionCard.tsx
Labels: release: minor, type: refactor
