Repository Caleydo/ordino, pull requests merged in 2021-05, with the labels that each got.

#294 Show current analysis session menu items and sort the menu
  dist/app/Ordino.js
  dist/app/Ordino.js.map
  dist/internal/OrdinoApp.d.ts
  dist/internal/OrdinoApp.js
  dist/internal/OrdinoApp.js.map
  dist/internal/components/session/CommonSessionCard.d.ts
  dist/internal/components/session/CommonSessionCard.js
  dist/internal/components/session/CommonSessionCard.js.map
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/phovea.js
  dist/phovea.js.map
  dist/scss/components/StartMenu.scss
  dist/scss/main.scss
  dist/scss/overrides/_header.scss
  dist/scss/overrides/header.scss
  src/app/Ordino.tsx
  src/internal/OrdinoApp.tsx
  src/internal/components/session/CommonSessionCard.tsx
  src/internal/components/session/CurrentSessionCard.tsx
  src/internal/menu/StartMenu.tsx
  src/phovea.ts
  src/scss/components/StartMenu.scss
  src/scss/main.scss
  src/scss/overrides/_header.scss
Labels: release: minor, type: refactor

#295 Replace Bootstrap scrollspy with intersection observer
  dist/internal/components/common/OrdinoScrollspy.d.ts
  dist/internal/components/common/OrdinoScrollspy.js
  dist/internal/components/common/OrdinoScrollspy.js.map
  dist/internal/menu/StartMenu.d.ts
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/internal/menu/tabs/DatasetsTab.d.ts
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.d.ts
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.d.ts
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  package.json
  src/internal/components/common/OrdinoScrollspy.tsx
  src/internal/components/tours/TourCard.tsx
  src/internal/menu/StartMenu.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
Labels: release: minor, type: bug, type: refactor

#297 Replace `react-bootstrap` with plain Bootstrap
  dist/components/HeaderNavigation.js
  dist/components/HeaderNavigation.js.map
  dist/components/ListItemDropdown.d.ts
  dist/components/ListItemDropdown.js
  dist/components/ListItemDropdown.js.map
  dist/hooks/useAsync.d.ts
  dist/internal/cmds.d.ts
  dist/internal/components/common/OrdinoScrollspy.js
  dist/internal/components/common/OrdinoScrollspy.js.map
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/internal/components/session/CommonSessionCard.d.ts
  dist/internal/components/session/CommonSessionCard.js
  dist/internal/components/session/CommonSessionCard.js.map
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/components/session/SessionListItem.js
  dist/internal/components/session/SessionListItem.js.map
  dist/internal/components/session/TemporarySessionCard.js
  dist/internal/components/session/TemporarySessionCard.js.map
  dist/internal/components/tours/TourCard.js
  dist/internal/components/tours/TourCard.js.map
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  src/components/HeaderNavigation.tsx
  src/components/ListItemDropdown.tsx
  src/internal/components/common/OrdinoScrollspy.tsx
  src/internal/components/dataset/NamedSetList.tsx
  src/internal/components/session/CommonSessionCard.tsx
  src/internal/components/session/CurrentSessionCard.tsx
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/components/session/SessionListItem.tsx
  src/internal/components/session/TemporarySessionCard.tsx
  src/internal/components/tours/TourCard.tsx
  src/internal/menu/StartMenu.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
Labels: type: refactor

#296 Add "Ordino at a Glance" page inside the app
  dist/app/Ordino.js
  dist/app/Ordino.js.map
  dist/base/extensions.d.ts
  dist/base/extensions.js
  dist/base/extensions.js.map
  dist/internal/menu/StartMenu.d.ts
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/internal/menu/tabs/DatasetsTab.d.ts
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.d.ts
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.d.ts
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  dist/phovea.js
  dist/phovea.js.map
  src/app/Ordino.tsx
  src/base/extensions.ts
  src/internal/menu/StartMenu.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
  src/phovea.ts
Labels: type: feature, type: refactor

#299 Fix OrdinoScrollspy typings
  dist/internal/components/common/OrdinoScrollspy.d.ts
  dist/internal/components/common/OrdinoScrollspy.js
  dist/internal/components/common/OrdinoScrollspy.js.map
  package.json
  src/internal/components/common/OrdinoScrollspy.tsx
Labels: release: patch, type: refactor

#298 Update footer links
  dist/components/OrdinoFooter.js
  dist/components/OrdinoFooter.js.map
  dist/hooks/index.d.ts
  dist/hooks/index.js
  dist/hooks/index.js.map
  dist/hooks/useScrollToSlug.d.ts
  dist/hooks/useScrollToSlug.js
  dist/hooks/useScrollToSlug.js.map
  src/components/OrdinoFooter.tsx
  src/hooks/index.ts
  src/hooks/useScrollToSlug.ts
Labels: release: minor, type: feature

#300 Add tooltip to the NamedSets buttons
  dist/internal/components/dataset/DatasetUtils.d.ts
  dist/internal/components/dataset/DatasetUtils.js
  dist/internal/components/dataset/DatasetUtils.js.map
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/internal/components/session/SessionListItem.js
  dist/internal/components/session/SessionListItem.js.map
  dist/scss/abstracts/_variables.scss
  src/internal/components/dataset/DatasetUtils.ts
  src/internal/components/dataset/NamedSetList.tsx
  src/internal/components/session/SessionListItem.tsx
  src/scss/abstracts/_variables.scss
Labels: release: minor, type: refactor

#301 Add `title` and `WAI ARIA` attributes to the StartMenu
  dist/internal/cmds.d.ts
  dist/internal/components/navigation/OrdinoBreadcrumbs.js
  dist/internal/components/navigation/OrdinoBreadcrumbs.js.map
  dist/internal/components/session/CommonSessionCard.d.ts
  dist/internal/components/session/CommonSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/components/session/SessionListItem.js
  dist/internal/components/session/SessionListItem.js.map
  dist/internal/components/session/TemporarySessionCard.js
  dist/internal/components/session/TemporarySessionCard.js.map
  dist/internal/components/tours/TourCard.js
  dist/internal/components/tours/TourCard.js.map
  dist/locales/en/tdp.json
  src/internal/components/dataset/NamedSetList.tsx
  src/internal/components/navigation/OrdinoBreadcrumbs.tsx
  src/internal/components/session/CommonSessionCard.tsx
  src/internal/components/session/CurrentSessionCard.tsx
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/components/session/SessionListItem.tsx
  src/internal/components/session/TemporarySessionCard.tsx
  src/internal/components/tours/TourCard.tsx
  src/locales/en/tdp.json
Labels: release: minor, type: feature
