Repository Caleydo/ordino, pull requests merged in 2021-11, with the labels that each got.

#341 Avoid reloading when saving current session
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  src/internal/components/session/CurrentSessionCard.tsx
Labels: type: refactor, release: patch

#342 Adapt use of useAsync
  dist/components/OrdinoLogo.js
  dist/components/OrdinoLogo.js.map
  dist/hooks/index.d.ts
  dist/hooks/index.js
  dist/hooks/index.js.map
  dist/hooks/useAsync.d.ts
  dist/hooks/useAsync.js
  dist/hooks/useAsync.js.map
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  dist/internal/components/session/TemporarySessionCard.js
  dist/internal/components/session/TemporarySessionCard.js.map
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.js
  dist/internal/menu/tabs/SessionsTab.js.map
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  src/components/OrdinoLogo.tsx
  src/hooks/index.ts
  src/hooks/useAsync.ts
  src/internal/components/session/SavedSessionCard.tsx
  src/internal/components/session/TemporarySessionCard.tsx
  src/internal/menu/StartMenu.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/internal/menu/tabs/SessionsTab.tsx
  src/internal/menu/tabs/ToursTab.tsx
Labels: type: refactor

#347 Fix missing scroll bar for other sessions
  dist/internal/components/session/SavedSessionCard.js
  dist/internal/components/session/SavedSessionCard.js.map
  src/internal/components/session/SavedSessionCard.tsx
Labels: type: bug, release: patch
