Repository Caleydo/ordino, pull requests merged in 2021-06, with the labels that each got.

#304 Semi-transparent background for start menu in overlay mode
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/scss/components/StartMenu.scss
  src/internal/menu/StartMenu.tsx
  src/scss/components/StartMenu.scss
Labels: release: minor, type: feature

#307 Hide CLUE mode selector + side panels when start menu is open
  dist/internal/cmds.d.ts
  dist/internal/menu/StartMenu.js
  dist/internal/menu/StartMenu.js.map
  dist/scss/overrides/_header.scss
  src/internal/menu/StartMenu.tsx
  src/scss/overrides/_header.scss
Labels: release: patch

#308 Hide help and tour link
  dist/app/Ordino.js
  dist/app/Ordino.js.map
  src/app/Ordino.tsx
Labels: type: feature

#309 Prepare reusage of tours
  dist/internal/components/tours/TourCard.d.ts
  dist/internal/components/tours/TourCard.js
  dist/internal/components/tours/TourCard.js.map
  dist/internal/menu/tabs/ToursTab.d.ts
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  src/internal/components/tours/TourCard.tsx
  src/internal/menu/tabs/ToursTab.tsx
Labels: type: feature

#311 Open welcome page in new tab with click on the Ordino icon in the start menu
  dist/app/Ordino.js
  dist/app/Ordino.js.map
  dist/locales/en/tdp.json
  src/app/Ordino.tsx
  src/locales/en/tdp.json
Labels: release: minor, type: feature

#312 Hide scrollspy on xxl breakpoint instead of xxxxl
  dist/internal/components/common/OrdinoScrollspy.js
  dist/internal/components/common/OrdinoScrollspy.js.map
  dist/scss/abstracts/_variables.scss
  src/internal/components/common/OrdinoScrollspy.tsx
  src/scss/abstracts/_variables.scss
Labels: release: minor, type: bug

#313 Hide close button for first view
  dist/scss/components/_targid.scss
  src/scss/components/_targid.scss
Labels: release: minor, type: feature

#314 Rename tour section from "Beginner" to "General introduction"
  dist/internal/menu/tabs/ToursTab.js
  dist/internal/menu/tabs/ToursTab.js.map
  dist/locales/en/tdp.json
  src/internal/menu/tabs/ToursTab.tsx
  src/locales/en/tdp.json
Labels: release: minor, type: feature
