Repository Caleydo/ordino, pull requests merged in 2022-05, with the labels that each got.

#386 Sort namedsets alphabetically and fix edit/delete named sets
  dist/base/extensions.d.ts
  dist/base/extensions.d.ts.map
  dist/components/HeaderNavigation.d.ts
  dist/components/HeaderNavigation.d.ts.map
  dist/components/OrdinoFooter.d.ts
  dist/components/OrdinoFooter.d.ts.map
  dist/components/OrdinoLogo.d.ts
  dist/components/OrdinoLogo.d.ts.map
  dist/internal/cmds.d.ts
  dist/internal/cmds.d.ts.map
  dist/internal/components/dataset/NamedSetList.d.ts.map
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/internal/components/navigation/OrdinoBreadcrumbs.d.ts
  dist/internal/components/navigation/OrdinoBreadcrumbs.d.ts.map
  dist/internal/components/session/CurrentSessionCard.d.ts
  dist/internal/components/session/CurrentSessionCard.d.ts.map
  dist/internal/components/session/SavedSessionCard.d.ts
  dist/internal/components/session/SavedSessionCard.d.ts.map
  dist/internal/components/session/SessionDropzone.d.ts
  dist/internal/components/session/SessionDropzone.d.ts.map
  dist/internal/components/session/TemporarySessionCard.d.ts
  dist/internal/components/session/TemporarySessionCard.d.ts.map
  dist/internal/components/session/UploadSessionCard.d.ts
  dist/internal/components/session/UploadSessionCard.d.ts.map
  dist/internal/menu/StartMenu.d.ts
  dist/internal/menu/StartMenu.d.ts.map
  dist/internal/menu/StartMenuLinks.d.ts
  dist/internal/menu/StartMenuLinks.d.ts.map
  dist/internal/menu/StartMenuTabWrapper.d.ts
  dist/internal/menu/StartMenuTabWrapper.d.ts.map
  dist/internal/menu/tabs/DatasetsTab.d.ts
  dist/internal/menu/tabs/DatasetsTab.d.ts.map
  dist/internal/menu/tabs/SessionsTab.d.ts
  dist/internal/menu/tabs/SessionsTab.d.ts.map
  dist/internal/menu/tabs/ToursTab.d.ts
  dist/internal/menu/tabs/ToursTab.d.ts.map
  dist/scss/abstracts/_variables.scss
  src/internal/components/dataset/NamedSetList.tsx
Labels: type: bug, release: patch

#389 Extract language string in dataset tab
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/locales/en/tdp.json
  src/internal/menu/tabs/DatasetsTab.tsx
  src/locales/en/tdp.json
Labels: type: refactor, release: minor

#378 External Vis Config Changes
  dist/app/workbench/WorkbenchGenericView.d.ts.map
  dist/app/workbench/WorkbenchGenericView.js
  dist/app/workbench/WorkbenchGenericView.js.map
  dist/store/storeUtils.d.ts.map
  dist/store/storeUtils.js
  dist/store/storeUtils.js.map
  dist/views/VisVisynView.js
  dist/views/VisVisynView.js.map
  src/app/workbench/WorkbenchGenericView.tsx
  src/store/storeUtils.ts
  src/views/VisVisynView.tsx
Labels: type: refactor

#390 Adding React Mosaic
  dist/app/Ordino.d.ts.map
  dist/app/Ordino.js
  dist/app/Ordino.js.map
  dist/app/workbench/MoveButton.d.ts.map
  dist/app/workbench/MoveButton.js
  dist/app/workbench/MoveButton.js.map
  dist/app/workbench/WorkbenchEmptyView.d.ts
  dist/app/workbench/WorkbenchEmptyView.d.ts.map
  dist/app/workbench/WorkbenchEmptyView.js
  dist/app/workbench/WorkbenchEmptyView.js.map
  dist/app/workbench/WorkbenchGenericView.d.ts
  dist/app/workbench/WorkbenchGenericView.d.ts.map
  dist/app/workbench/WorkbenchGenericView.js
  dist/app/workbench/WorkbenchGenericView.js.map
  dist/app/workbench/WorkbenchView.d.ts
  dist/app/workbench/WorkbenchView.d.ts.map
  dist/app/workbench/WorkbenchView.js
  dist/app/workbench/WorkbenchView.js.map
  dist/app/workbench/WorkbenchViews.d.ts.map
  dist/app/workbench/WorkbenchViews.js
  dist/app/workbench/WorkbenchViews.js.map
  dist/components/breadcrumb/SingleBreadcrumb.d.ts.map
  dist/components/breadcrumb/SingleBreadcrumb.js
  dist/components/breadcrumb/SingleBreadcrumb.js.map
  dist/scss/components/Workbench.scss
  dist/scss/main.scss
  dist/scss/vendors/_react-mosaic.scss
  dist/views/CosmicProxyView.d.ts.map
  dist/views/CosmicProxyView.js
  dist/views/CosmicProxyView.js.map
  dist/views/VisVisynView.d.ts
  dist/views/VisVisynView.d.ts.map
  dist/views/VisVisynView.js
  dist/views/VisVisynView.js.map
  package.json
  src/app/Ordino.tsx
  src/app/workbench/DropOverlay.tsx
  src/app/workbench/MoveButton.tsx
  src/app/workbench/WorkbenchEmptyView.tsx
  src/app/workbench/WorkbenchGenericView.tsx
  src/app/workbench/WorkbenchView.tsx
  src/app/workbench/WorkbenchViews.tsx
  src/app/workbench/icons/WorkbenchSwitchIcon.tsx
  src/components/breadcrumb/SingleBreadcrumb.tsx
  src/scss/components/Workbench.scss
  src/scss/main.scss
  src/scss/vendors/_react-mosaic.scss
  src/views/CosmicProxyView.tsx
  src/views/VisVisynView.tsx
Labels: type: refactor

#391 Hide the close button in breadcrumb for the first workbench
  dist/components/breadcrumb/SingleBreadcrumb.d.ts.map
  dist/components/breadcrumb/SingleBreadcrumb.js
  dist/components/breadcrumb/SingleBreadcrumb.js.map
  src/components/breadcrumb/SingleBreadcrumb.tsx
Labels: type: feature, release: patch

#395 Hide `.phovea-navbar` from `AppHeader` in `useLoginMenu`
  dist/visyn/hooks/useLoginMenu.d.ts.map
  dist/visyn/hooks/useLoginMenu.js
  dist/visyn/hooks/useLoginMenu.js.map
  src/visyn/hooks/useLoginMenu.ts
Labels: type: bug, release: patch

#398 Fix empty mosaic views and open comments panel when re-open workbench
  dist/app/workbench/WorkbenchViews.d.ts.map
  dist/app/workbench/WorkbenchViews.js
  dist/app/workbench/WorkbenchViews.js.map
  dist/app/workbench/useCommentPanel.d.ts.map
  dist/app/workbench/useCommentPanel.js
  dist/app/workbench/useCommentPanel.js.map
  dist/components/breadcrumb/SingleBreadcrumb.js
  dist/components/breadcrumb/SingleBreadcrumb.js.map
  dist/store/ordinoSlice.d.ts
  dist/store/ordinoSlice.d.ts.map
  dist/store/ordinoSlice.js
  dist/store/ordinoSlice.js.map
  dist/store/workbenchReducer.d.ts
  dist/store/workbenchReducer.d.ts.map
  dist/store/workbenchReducer.js
  dist/store/workbenchReducer.js.map
  src/app/workbench/WorkbenchViews.tsx
  src/app/workbench/useCommentPanel.ts
  src/components/breadcrumb/SingleBreadcrumb.tsx
  src/store/ordinoSlice.ts
  src/store/workbenchReducer.ts
Labels: type: bug, priority: blocker, release: patch
