Repository Caleydo/ordino, pull requests merged in 2022-08, with the labels that each got.

#415 Remove `nav.mainNavi` styles
  dist/scss/components/_targid.scss
  src/scss/components/_targid.scss
Labels: type: technical debt, release: patch

#420 Release 12.1.0
  .circleci/config.yml
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  dist/internal/cmds.d.ts
  dist/internal/cmds.d.ts.map
  dist/internal/cmds.js
  dist/internal/cmds.js.map
  dist/scss/components/_targid.scss
  package.json
  src/internal/ViewWrapper.ts
  src/internal/cmds.ts
  src/scss/components/_targid.scss
Labels: release: minor

#419 feat: CLUE support for URL query parameter + refactor public session link
  dist/internal/cmds.d.ts
  dist/internal/cmds.d.ts.map
  dist/internal/components/session/CurrentSessionCard.d.ts.map
  dist/internal/components/session/CurrentSessionCard.js
  dist/internal/components/session/CurrentSessionCard.js.map
  src/internal/components/session/CurrentSessionCard.tsx
Labels: type: feature, release: minor

#425 fix: Replace jQuery scrollTo plugin with custom implementation
  .yo-rc.json
  dist/internal/ViewWrapper.d.ts
  dist/internal/ViewWrapper.d.ts.map
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  package.json
  src/internal/ViewWrapper.ts
Labels: type: bug, type: technical debt, release: minor
