Repository Caleydo/ordino, pull requests merged in 2022-06, with the labels that each got.

#404 Release 12.0.0
  dist/base/extensions.d.ts
  dist/base/extensions.d.ts.map
  dist/components/HeaderNavigation.d.ts
  dist/components/HeaderNavigation.d.ts.map
  dist/components/OrdinoFooter.d.ts
  dist/components/OrdinoFooter.d.ts.map
  dist/components/OrdinoLogo.d.ts
  dist/components/OrdinoLogo.d.ts.map
  dist/internal/OrdinoApp.d.ts
  dist/internal/OrdinoApp.d.ts.map
  dist/internal/OrdinoApp.js
  dist/internal/OrdinoApp.js.map
  dist/internal/cmds.d.ts
  dist/internal/cmds.d.ts.map
  dist/internal/components/dataset/NamedSetList.d.ts
  dist/internal/components/dataset/NamedSetList.d.ts.map
  dist/internal/components/dataset/NamedSetList.js
  dist/internal/components/dataset/NamedSetList.js.map
  dist/internal/components/navigation/OrdinoBreadcrumbs.d.ts
  dist/internal/components/navigation/OrdinoBreadcrumbs.d.ts.map
  dist/internal/components/session/CurrentSessionCard.d.ts
  dist/internal/components/session/CurrentSessionCard.d.ts.map
  dist/internal/components/session/SavedSessionCard.d.ts
  dist/internal/components/session/SavedSessionCard.d.ts.map
  dist/internal/components/session/SessionDropzone.d.ts
  dist/internal/components/session/SessionDropzone.d.ts.map
  dist/internal/components/session/TemporarySessionCard.d.ts
  dist/internal/components/session/TemporarySessionCard.d.ts.map
  dist/internal/components/session/UploadSessionCard.d.ts
  dist/internal/components/session/UploadSessionCard.d.ts.map
  dist/internal/menu/StartMenu.d.ts
  dist/internal/menu/StartMenu.d.ts.map
  dist/internal/menu/StartMenuLinks.d.ts
  dist/internal/menu/StartMenuLinks.d.ts.map
  dist/internal/menu/StartMenuTabWrapper.d.ts
  dist/internal/menu/StartMenuTabWrapper.d.ts.map
  dist/internal/menu/tabs/DatasetsTab.d.ts
  dist/internal/menu/tabs/DatasetsTab.d.ts.map
  dist/internal/menu/tabs/DatasetsTab.js
  dist/internal/menu/tabs/DatasetsTab.js.map
  dist/internal/menu/tabs/SessionsTab.d.ts
  dist/internal/menu/tabs/SessionsTab.d.ts.map
  dist/internal/menu/tabs/ToursTab.d.ts
  dist/internal/menu/tabs/ToursTab.d.ts.map
  dist/locales/en/tdp.json
  dist/scss/abstracts/_variables.scss
  package.json
  src/internal/OrdinoApp.tsx
  src/internal/components/dataset/NamedSetList.tsx
  src/internal/menu/tabs/DatasetsTab.tsx
  src/locales/en/tdp.json
Labels: release: major

#346 React LoginMenu
  dist/components/OrdinoHeader.d.ts
  dist/components/OrdinoHeader.d.ts.map
  dist/components/OrdinoHeader.js
  dist/components/OrdinoHeader.js.map
  dist/visyn/BusyOverlay.d.ts
  dist/visyn/BusyOverlay.d.ts.map
  dist/visyn/BusyOverlay.js
  dist/visyn/BusyOverlay.js.map
  dist/visyn/LoginMenu.d.ts
  dist/visyn/LoginMenu.d.ts.map
  dist/visyn/LoginMenu.js
  dist/visyn/LoginMenu.js.map
  dist/visyn/VisynApp.d.ts
  dist/visyn/VisynApp.d.ts.map
  dist/visyn/VisynApp.js
  dist/visyn/VisynApp.js.map
  dist/visyn/VisynHeader.d.ts.map
  dist/visyn/VisynHeader.js
  dist/visyn/VisynHeader.js.map
  dist/visyn/headerComponents/LoginDialog.d.ts
  dist/visyn/headerComponents/LoginDialog.d.ts.map
  dist/visyn/headerComponents/LoginDialog.js
  dist/visyn/headerComponents/LoginDialog.js.map
  dist/visyn/headerComponents/VisynLoginForm.d.ts
  dist/visyn/headerComponents/VisynLoginForm.d.ts.map
  dist/visyn/headerComponents/VisynLoginForm.js
  dist/visyn/headerComponents/VisynLoginForm.js.map
  dist/visyn/headerComponents/index.d.ts
  dist/visyn/headerComponents/index.d.ts.map
  dist/visyn/headerComponents/index.js
  dist/visyn/headerComponents/index.js.map
  dist/visyn/index.d.ts
  dist/visyn/index.d.ts.map
  dist/visyn/index.js
  dist/visyn/index.js.map
  dist/visyn/usersSlice.d.ts
  dist/visyn/usersSlice.d.ts.map
  dist/visyn/usersSlice.js
  dist/visyn/usersSlice.js.map
  src/components/OrdinoHeader.tsx
  src/visyn/BusyOverlay.tsx
  src/visyn/LoginMenu.tsx
  src/visyn/VisynApp.tsx
  src/visyn/VisynHeader.tsx
  src/visyn/headerComponents/LoginDialog.tsx
  src/visyn/headerComponents/VisynLoginForm.tsx
  src/visyn/headerComponents/index.ts
  src/visyn/index.ts
  src/visyn/usersSlice.ts
Labels: type: refactor, release: minor

#405 Fix app crash when replacing views with object ref from `graph.findOrAddObject()`
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  src/internal/ViewWrapper.ts
Labels: type: bug, release: patch
