Repository Caleydo/ordino, pull requests merged in 2022-04, with the labels that each got.

#367 Add comments panel to workbench
  dist/app/Workbench.d.ts.map
  dist/app/Workbench.js
  dist/app/Workbench.js.map
  dist/app/workbench/WorkbenchViews.d.ts.map
  dist/app/workbench/WorkbenchViews.js
  dist/app/workbench/WorkbenchViews.js.map
  dist/app/workbench/useCommentPanel.d.ts
  dist/app/workbench/useCommentPanel.d.ts.map
  dist/app/workbench/useCommentPanel.js
  dist/app/workbench/useCommentPanel.js.map
  dist/components/breadcrumb/OpenCommentsButton.d.ts
  dist/components/breadcrumb/OpenCommentsButton.d.ts.map
  dist/components/breadcrumb/OpenCommentsButton.js
  dist/components/breadcrumb/OpenCommentsButton.js.map
  dist/components/breadcrumb/SingleBreadcrumb.d.ts.map
  dist/components/breadcrumb/SingleBreadcrumb.js
  dist/components/breadcrumb/SingleBreadcrumb.js.map
  dist/locales/en/tdp.json
  dist/phovea.d.ts.map
  dist/phovea.js
  dist/phovea.js.map
  dist/scss/components/Workbench.scss
  dist/store/ordinoSlice.d.ts
  dist/store/ordinoSlice.d.ts.map
  dist/store/ordinoSlice.js
  dist/store/ordinoSlice.js.map
  package.json
  src/app/Workbench.tsx
  src/app/workbench/WorkbenchViews.tsx
  src/app/workbench/useCommentPanel.ts
  src/components/breadcrumb/OpenCommentsButton.tsx
  src/components/breadcrumb/SingleBreadcrumb.tsx
  src/locales/en/tdp.json
  src/phovea.ts
  src/scss/components/Workbench.scss
  src/store/ordinoSlice.ts
Labels: type: feature, release: minor

#369 Adding word "Workbench" to breadcrumb
  dist/components/breadcrumb/SingleBreadcrumb.d.ts.map
  dist/components/breadcrumb/SingleBreadcrumb.js
  dist/components/breadcrumb/SingleBreadcrumb.js.map
  dist/locales/en/tdp.json
  dist/phovea.d.ts.map
  dist/phovea.js
  dist/phovea.js.map
  dist/views/VisVisynView.d.ts.map
  src/components/breadcrumb/SingleBreadcrumb.tsx
  src/locales/en/tdp.json
  src/phovea.ts
Labels: type: feature

#375 Use `npm-force-resolutions` to pin `@types/react` in sub-dependencies to v17.0.44
  .circleci/config.yml
  package.json
Labels: type: bug, priority: high, type: technical debt

#373 Update Column Infos
  dist/app/workbench/WorkbenchGenericView.d.ts.map
  dist/app/workbench/WorkbenchGenericView.js
  dist/app/workbench/WorkbenchGenericView.js.map
  dist/app/workbench/sidebar/CreateNextWorkbenchSidebar.d.ts.map
  dist/app/workbench/sidebar/CreateNextWorkbenchSidebar.js
  dist/app/workbench/sidebar/CreateNextWorkbenchSidebar.js.map
  dist/app/workbench/sidebar/DetailsSidebar.d.ts.map
  dist/app/workbench/sidebar/DetailsSidebar.js
  dist/app/workbench/sidebar/DetailsSidebar.js.map
  dist/store/ordinoSlice.d.ts
  dist/store/ordinoSlice.d.ts.map
  dist/store/ordinoSlice.js
  dist/store/ordinoSlice.js.map
  dist/views/VisVisynView.js
  dist/views/VisVisynView.js.map
  dist/views/interfaces.d.ts
  dist/views/interfaces.d.ts.map
  dist/views/interfaces.js.map
  src/app/workbench/WorkbenchGenericView.tsx
  src/app/workbench/sidebar/CreateNextWorkbenchSidebar.tsx
  src/app/workbench/sidebar/DetailsSidebar.tsx
  src/store/ordinoSlice.ts
  src/views/VisVisynView.tsx
  src/views/interfaces.ts
Labels: type: feature

#357 Skip detail view chooser if only one detail view is available
  dist/internal/ViewWrapper.d.ts.map
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  dist/scss/abstracts/_variables.scss
  dist/scss/components/_targid.scss
  src/internal/ViewWrapper.ts
  src/scss/components/_targid.scss
Labels: type: feature, release: minor

#370 Rename `dataDesc` to `columnDesc` in VisynDataView
  dist/app/workbench/WorkbenchGenericView.js
  dist/app/workbench/WorkbenchGenericView.js.map
  dist/store/ordinoSlice.d.ts
  dist/store/ordinoSlice.d.ts.map
  dist/views/VisVisynView.d.ts
  dist/views/VisVisynView.d.ts.map
  dist/views/VisVisynView.js
  dist/views/VisVisynView.js.map
  dist/views/interfaces.d.ts
  dist/views/interfaces.d.ts.map
  package.json
  src/app/workbench/WorkbenchGenericView.tsx
  src/views/VisVisynView.tsx
  src/views/interfaces.ts
Labels: type: refactor

#382 Revert "Skip detail view chooser if only one detail view is available"
  dist/internal/ViewWrapper.d.ts.map
  dist/internal/ViewWrapper.js
  dist/internal/ViewWrapper.js.map
  dist/scss/abstracts/_variables.scss
  dist/scss/components/_targid.scss
  src/internal/ViewWrapper.ts
  src/scss/components/_targid.scss
Labels: type: bug, release: minor

#377 Add close button to workbenches
  dist/components/breadcrumb/SingleBreadcrumb.d.ts.map
  dist/components/breadcrumb/SingleBreadcrumb.js
  dist/components/breadcrumb/SingleBreadcrumb.js.map
  dist/locales/en/tdp.json
  dist/store/ordinoSlice.d.ts
  dist/store/ordinoSlice.d.ts.map
  dist/store/ordinoSlice.js
  dist/store/ordinoSlice.js.map
  dist/store/workbenchReducer.js
  dist/store/workbenchReducer.js.map
  src/components/breadcrumb/SingleBreadcrumb.tsx
  src/locales/en/tdp.json
  src/store/ordinoSlice.ts
  src/store/workbenchReducer.ts
Labels: type: feature, release: minor
